class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all

    current_user_profils = current_user.profils
    restrictions = Restriction.joins(profils: :user).where(users: { id: current_user.id }).pluck(:name)
    preferences_dislike = Ingredient.joins(profils: :user).where(users: { id: current_user.id }, preferences: { like: false } ).pluck(:name)
    preferences_like = Ingredient.joins(profils: :user).where(users: { id: current_user.id }, preferences: { like: true } ).pluck(:name)
    diet = Diet.joins(profils: :user).where(users: { id: current_user.id }).pluck(:name)
    target = Target.joins(profils: :user).where(users: { id: current_user.id }).pluck(:name)

    client = OpenAI::Client.new
    chaptgpt_response = client.chat(parameters: {
      model: "gpt-4o",
      messages: [{ role: "user", content:
        "génère 6 recettes de cuisine qui conviennent pour des personnes avec des régimes alimentaires différents: #{diet}
        Qui ne peuvent absolument pas manger (allergies et intolérance): #{restrictions}
        Qui aiment bien manger entres autres: #{preferences_like}
        Qui n'aiment pas: #{preferences_dislike}
        Qui ont des niveaux de difficultés: 3 faciles, 2 moyennnes, 1 difficile.
        Formate la recette en json avec:
        hash de recette {name: 'le nom de la recette', description: 'appétissante de la recette en 150 caractères maximum', temps: 'temps de réalisation de la recette', niveau: 'niveau de difficulté de la recette', Kcal_tot: 'calorie totale en Kcal de la recette pour tous les ingrédients', type: 'spécialité de la recette, par exemple française, japonaise etc..' }
        hash des ustensiles: { utensil: 'nom', description: 'type de l'ustensile' }
        Hash des ingrédients { name: 'nom de l’ingrédient', quantity: 'quantité pour la recette', Kcal: 'calories correspondantes à la  quantité de la recette en Kcal', Kcal_100g: 'calories pour 100g de l’ingrédient' }
        un hash de step_by_step de la recette: {step: 'étape de la recette', description: 'instruction détaillée de l'étape de la recette en 250 caractères minimum et 600 caractères maximum'}
        Je veux seulement un json par recette sans texte d'introduction ou de conclusion."
          }]
      })
    chaptgpt_response["choices"][0]["message"]["content"]

   raise

  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

x
>> chaptgpt_response
=> {"id"=>"chatcmpl-9cXwer94uO4ac4avzSlJEEwvUXQDM", "object"=>"chat.completion", "created"=>1718973976, "model"=>"gpt-4o-2024-05-13", "choices"=>[{"index"=>0, "message"=>{"role"=>"assistant",
  "content"=>"```
  json\n{\n  \"recipe\": {\n    \"name\": \"Salade Caprese Sans Gluten\",\n    \"description\": \"Une salade italienne classique et rafraîchissante avec des tomates et de la mozzarella.\",\n    \"temps\": \"15 minutes\",\n    \"niveau\": \"Facile\",\n    \"Kcal_tot\": 300,\n    \"type\": \"italienne\"\n  },\n  \"utensils\": [\n    {\"utensil\": \"couteau\", \"description\": \"couteau pour couper les ingrédients\"},\n    {\"utensil\": \"planche à découper\", \"description\": \"planche pour couper les ingrédients\"},\n    {\"utensil\": \"bol\", \"description\": \"bol pour mélanger les ingrédients\"}\n  ],\n  \"ingredients\": [\n    {\"name\": \"tomates\", \"quantity\": \"4 unités\", \"Kcal\": 96, \"Kcal_100g\": 18},\n    {\"name\": \"mozzarella\", \"quantity\": \"200 g\", \"Kcal\": 160, \"Kcal_100g\": 73},\n    {\"name\": \"basilic frais\", \"quantity\": \"10 feuilles\", \"Kcal\": 2, \"Kcal_100g\": 23},\n    {\"name\": \"huile d'olive\", \"quantity\": \"2 cuillères à soupe\", \"Kcal\": 80, \"Kcal_100g\": 884},\n    {\"name\": \"sel et poivre\", \"quantity\": \"au goût\", \"Kcal\": 0, \"Kcal_100g\": 0}\n  ],\n  \"step_by_step\": [\n    {\"step\": 1, \"description\": \"Lavez et séchez les tomates et le basilic. Coupez les tomates en tranches épaisses.\"},\n    {\"step\": 2, \"description\": \"Coupez la mozzarella en tranches égales. Disposez les tranches de tomates et de mozzarella en alternance sur un plat de service.\"},\n    {\"step\": 3, \"description\": \"Parsemez de feuilles de basilic frais. Assaisonnez avec du sel et du poivre selon votre goût.\"},\n    {\"step\": 4, \"description\": \"Versez l'huile d'olive en filet sur la salade. Servez immédiatement pour profiter de la fraîcheur des ingrédients.\"}\n  ]\n}\n```\n\n```
  json\n{\n  \"recipe\": {\n    \"name\": \"Ratatouille Provençale\",\n    \"description\": \"Un délicieux mélange de légumes mijotés à la provençale, parfait pour un repas végétarien.\",\n    \"temps\": \"45 minutes\",\n    \"niveau\": \"Moyen\",\n    \"Kcal_tot\": 250,\n    \"type\": \"française\"\n  },\n  \"utensils\": [\n    {\"utensil\": \"couteau\", \"description\": \"couteau pour couper les légumes\"},\n    {\"utensil\": \"poêle à frire\", \"description\": \"poêle pour cuire les légumes\"},\n    {\"utensil\": \"spatule\", \"description\": \"spatule pour mélanger les légumes\"}\n  ],\n  \"ingredients\": [\n    {\"name\": \"aubergine\", \"quantity\": \"1 unité\", \"Kcal\": 20, \"Kcal_100g\": 24},\n    {\"name\": \"courgette\", \"quantity\": \"1 unité\", \"Kcal\": 17, \"Kcal_100g\": 16},\n    {\"name\": \"poivron\", \"quantity\": \"1 unité\", \"Kcal\": 25, \"Kcal_100g\": 20},\n    {\"name\": \"tomates\", \"quantity\": \"4 unités\", \"Kcal\": 96, \"Kcal_100g\": 18},\n    {\"name\": \"oignon\", \"quantity\": \"1 unité\", \"Kcal\": 40, \"Kcal_100g\": 40},\n    {\"name\": \"ail\", \"quantity\": \"2 gousses\", \"Kcal\": 10, \"Kcal_100g\": 149},\n    {\"name\": \"huile d'olive\", \"quantity\": \"2 cuillères à soupe\", \"Kcal\": 80, \"Kcal_100g\": 884},\n    {\"name\": \"herbes de Provence\", \"quantity\": \"1 cuillère à café\", \"Kcal\": 2, \"Kcal_100g\": 100},\n    {\"name\": \"sel et poivre\", \"quantity\": \"au goût\", \"Kcal\": 0, \"Kcal_100g\": 0}\n  ],\n  \"step_by_step\": [\n    {\"step\": 1, \"description\": \"Lavez et découpez tous les légumes en dés. Émincez l'oignon et l'ail.\"},\n    {\"step\": 2, \"description\": \"Chauffez l'huile d'olive dans une poêle à feu moyen. Ajoutez l'ail et l'oignon et faites revenir jusqu'à ce qu'ils soient dorés.\"},\n    {\"step\": 3, \"description\": \"Ajoutez l'aubergine, la courgette et le poivron. Faites sauter pendant environ 10 minutes jusqu'à ce que les légumes commencent à ramollir.\"},\n    {\"step\": 4, \"description\": \"Ajoutez les tomates et les herbes de Provence. Assaisonnez avec du sel et du poivre. Laissez mijoter à feu doux pendant 20 à 25 minutes en remuant de temps en temps.\"}\n  ]\n}\n```\n\n```
  json\n{\n  \"recipe\": {\n    \"name\": \"Soupe de Tomates à la Basilic\",\n    \"description\": \"Une soupe crémeuse et réchauffante à base de tomates et de basilic frais.\",\n    \"temps\": \"40 minutes\",\n    \"niveau\": \"Facile\",\n    \"Kcal_tot\": 200,\n    \"type\": \"méditerranéenne\"\n  },\n  \"utensils\": [\n    {\"utensil\": \"casserole\", \"description\": \"casserole pour cuire les légumes\"},\n    {\"utensil\": \"mixeur\", \"description\": \"mixeur pour réduire la soupe en purée\"},\n    {\"utensil\": \"couteau\", \"description\": \"couteau pour couper les légumes\"}\n  ],\n  \"ingredients\": [\n    {\"name\": \"tomates\", \"quantity\": \"6 unités\", \"Kcal\": 144, \"Kcal_100g\": 18},\n    {\"name\": \"oignon\", \"quantity\": \"1 unité\", \"Kcal\": 40, \"Kcal_100g\": 40},\n    {\"name\": \"ail\", \"quantity\": \"2 gousses\", \"Kcal\": 10, \"Kcal_100g\": 149},\n    {\"name\": \"basilic frais\", \"quantity\": \"10 feuilles\", \"Kcal\": 2, \"Kcal_100g\": 23},\n    {\"name\": \"huile d'olive\", \"quantity\": \"1 cuillère à soupe\", \"Kcal\": 40, \"Kcal_100g\": 884},\n    {\"name\": \"eau\", \"quantity\": \"1 litre\", \"Kcal\": 0, \"Kcal_100g\": 0},\n    {\"name\": \"sel et poivre\", \"quantity\": \"au goût\", \"Kcal\": 0, \"Kcal_100g\": 0}\n  ],\n  \"step_by_step\": [\n    {\"step\": 1, \"description\": \"Émincez l'oignon et l'ail. Lavez et découpez les tomates en quartiers.\"},\n    {\"step\": 2, \"description\": \"Chauffez l'huile d'olive dans une casserole à feu moyen. Ajoutez l'oignon et l'ail, faites revenir jusqu'à ce qu'ils soient dorés.\"},\n    {\"step\": 3, \"description\": \"Ajoutez les tomates dans la casserole. Faites cuire pendant 10 minutes en remuant régulièrement jusqu'à ce qu'elles soient tendres.\"},\n    {\"step\": 4, \"description\": \"Ajoutez le basilic, une pincée de sel, et l'eau. Portez à ébullition puis laissez mijoter à feu doux pendant 20 minutes.\"},\n    {\"step\": 5, \"description\": \"Mixez la soupe avec un mixeur jusqu'à obtenir une texture lisse et crémeuse. Rectifiez l'assaisonnement avec du sel et du poivre avant de servir.\"}\n  ]\n}\n```\n\n```
  json\n{\n  \"recipe\": {\n    \"name\": \"Tian de Légumes\",\n    \"description\": \"Un gratin de légumes coloré et savoureux, parfait pour accompagner un plat principal.\",\n    \"temps\": \"50 minutes\",\n    \"niveau\": \"Moyen\",\n    \"Kcal_tot\": 350,\n    \"type\": \"provençale\"\n  },\n  \"utensils\": [\n    {\"utensil\": \"couteau\", \"description\": \"couteau pour couper les légumes\"},\n    {\"utensil\": \"planche à découper\", \"description\": \"planche pour couper les légumes\"},\n    {\"utensil\": \"plat à gratin\", \"description\": \"plat pour cuire les légumes au four\"},\n    {\"utensil\": \"four\", \"description\": \"four pour cuire les légumes\"}\n  ],\n  \"ingredients\": [\n    {\"name\": \"aubergine\", \"quantity\": \"1 unité\", \"Kcal\": 20, \"Kcal_100g\": 24},\n    {\"name\": \"courgette\", \"quantity\": \"1 unité\", \"Kcal\": 17, \"Kcal_100g\": 16},\n    {\"name\": \"tomates\", \"quantity\": \"4 unités\", \"Kcal\": 96, \"Kcal_100g\": 18},\n    {\"name\": \"poivron\", \"quantity\": \"1 unité\", \"Kcal\": 25, \"Kcal_100g\": 20},\n    {\"name\": \"oignon\", \"quantity\": \"1 unité\", \"Kcal\": 40, \"Kcal_100g\": 40},\n    {\"name\": \"ail\", \"quantity\": \"2 gousses\", \"Kcal\": 10, \"Kcal_100g\": 149},\n    {\"name\": \"huile d'olive\", \"quantity\": \"2 cuillères à soupe\", \"Kcal\": 80, \"Kcal_100g\": 884},\n    {\"name\": \"herbes de Provence\", \"quantity\": \"1 cuillère à café\", \"Kcal\": 2, \"Kcal_100g\": 100},\n    {\"name\": \"sel et poivre\", \"quantity\": \"au goût\", \"Kcal\": 0, \"Kcal_100g\": 0}\n  ],\n  \"step_by_step\": [\n    {\"step\": 1, \"description\": \"Préchauffez le four à 180°C. Lavez et découpez les légumes en fines rondelles.\"},\n    {\"step\": 2, \"description\": \"Disposez les rondelles de légumes en couches alternées dans un plat à gratin.\"},\n    {\"step\": 3, \"description\": \"Émincez l'oignon et l'ail et répartissez-les uniformément sur les légumes. Arrosez le tout d'huile d'olive, saupoudrez d'herbes de Provence, de sel et de poivre.\"},\n    {\"step\": 4, \"description\": \"Couvrez le plat avec un papier d'aluminium. Enfournez pour 40 minutes. Retirez le papier d'aluminium et laissez cuire encore 10 minutes pour gratiner légèrement.\"}\n  ]\n}\n```\n\n```
  json\n{\n  \"recipe\": {\n    \"name\": \"Poivrons Farcis au Fromage\",\n    \"description\": \"Des poivrons farcis avec un mélange crémeux de fromage et d'herbes.\",\n    \"temps\": \"35 minutes\",\n    \"niveau\": \"Facile\",\n    \"Kcal_tot\": 400,\n    \"type\": \"méditerranéenne\"\n  },\n  \"utensils\": [\n    {\"utensil\": \"couteau\", \"description\": \"couteau pour couper les poivrons\"},\n    {\"utensil\": \"planche à découper\", \"description\": \"planche pour couper les poivrons\"},\n    {\"utensil\": \"four\", \"description\": \"four pour cuire les poivrons farcis\"}\n  ],\n  \"ingredients\": [\n    {\"name\": \"poivron\", \"quantity\": \"4 unités\", \"Kcal\": 100, \"Kcal_100g\": 20},\n    {\"name\": \"fromage à la crème\", \"quantity\": \"200 g\", \"Kcal\": 200, \"Kcal_100g\": 100},\n    {\"name\": \"basilic frais\", \"quantity\": \"10 feuilles\", \"Kcal\": 2, \"Kcal_100g\": 23},\n    {\"name\": \"huile d'olive\", \"quantity\": \"1 cuillère à soupe\", \"Kcal\": 40, \"Kcal_100g\": 884},\n    {\"name\": \"sel et poivre\", \"quantity\": \"au goût\", \"Kcal\": 0, \"Kcal_100g\": 0}\n  ],\n  \"step_by_step\": [\n    {\"step\": 1, \"description\": \"Préchauffez le four à 180°C. Lavez les poivrons, puis découpez le haut et retirez les graines et les membranes internes.\"},\n    {\"step\": 2, \"description\": \"Mélangez le fromage à la crème avec du basilic frais haché, du sel et du poivre jusqu'à obtenir une préparation homogène.\"},\n    {\"step\": 3, \"description\": \"Farcissez les poivrons avec le mélange de fromage. Disposez-les dans un plat allant au four.\"},\n    {\"step\": 4, \"description\": \"Arrosez d'huile d'olive sur les poivrons farcis. Enfournez pendant 25 minutes jusqu'à ce que les poivrons soient tendres et légèrement dorés sur le dessus.\"}\n  ]\n}\n```"}, "logprobs"=>nil, "finish_reason"=>"stop"}], "usage"=>{"prompt_tokens"=>338, "completion_tokens"=>3026, "total_tokens"=>3364},
